### ISSUE TITLE
Chat for this project

### ISSUE THREAD

**Issue by teunw** [mikaelbr/open-source-ideas#17]
## Project description

A chat for this repository, so that we can chat instead of submitting issue comments.
Different issues can use different 'channels'.

## Relevant Technology

Slack seems good, although in the spirit of the project a custom solution could be developed as well.

## Who is this for

People contributing to this project.

**Comment by FredrikAugust** [comment]
Wow, was just about to submit the exact same issue :) Slack seems like the easiest and probably the best.

**Comment by teunw** [comment]
@FredrikAugust 
Great minds think alike ;).
I think it's a better idea for @mikaelbr to create it, he's the project owner after all.

**Comment by mikaelbr** [comment]
Slack works good. 👍 One limiting factor however is that it's invite only. You could use something like https://github.com/rauchg/slackin, but that requires hosting (and free Heroku dyno will be limiting for this. I've used before and ended up having to pay for it for it to be usable). Could Discord (https://discordapp.com/) be an alternative? Or Matter Most? Or should we just go for Slack?

**Comment by teunw** [comment]
@mikaelbr 
Completely forgot about Discord, seems better than invite only. 
Could hold people back from joining.

**Comment by FredrikAugust** [comment]
Or, as I would definitely prefer, IRC :)

**Comment by FredrikAugust** [comment]
Then we could also create bots for added functionality

**Comment by FredrikAugust** [comment]
Another possibililty is using telegram, which is quite nice on mobile/tablet/web/desktop app.

**Comment by priithaamer** [comment]
I'd be in favor of Slack as it is most probably running for most of us already...

**Comment by FredrikAugust** [comment]
Indeed, irc doesn't require any setup or similar though, and it's really easy for people to join.

**Comment by teunw** [comment]
True, I don't think we need stuff like voice chat tbh.

**Comment by SebastianKeller** [comment]
@FredrikAugust What about #open-source-ideas on freenode?

**Comment by FredrikAugust** [comment]
@SebastianKeller Sounds great to me, IMO that is the simplest and best solution, but everyone to themselves I guess. I'll be there if anyone needs me :)

**Comment by mikaelbr** [comment]
I just did this to make it simple: https://opensourceideas.herokuapp.com/

Reasoning is that I think most people already have Slack open, and it's now become more accessible than IRC. Even though many still are on IRC I think Slack has become more what "many new developers get introduced to first". Also, there is a gateway from Slack to IRC, but harder to do the other way around.

**Comment by FredrikAugust** [comment]
If you can setup Slack -> IRC then I could do IRC -> Slack. Recently did IRC -> Telegram, and it's not that hard really.

**Comment by mikaelbr** [comment]
This is now done and can be closed 👍
