### ISSUE TITLE
slack-notify: CLI for sending messages on Slack

### ISSUE THREAD

**Issue by mikaelbr** [mikaelbr/open-source-ideas#2]
**This idea has been claimed and implemented by @dinodsaurus. Found at  https://github.com/twobucks/slack-message.** 🍰 

---

## Project description

A minimal CLI for sending messages to a slack team and channel. This can be used as a general, CI agnostic, tool to notify a Slack channel when a operation is done. For instance when some tests fails on a Travis Build, when a new version is deployed to a production environment or what ever.

I'm envisioning something like this:

```
slack-message "team-name" "channel" "My message here"
```

Maybe there should be some AUTH in a rc file or as a part of the interface.

## Relevant Technology

What ever the developer would like to use. This is a great opportunity to test out a new platform/language. It should be easily installable on all platforms and CI systems. It's easy to think Node.js/NPM for this, but there are other options also.

## Who is this for

Anyone interested in testing out the Slack API and creating CLIs. Not much work and it can be implemented very specifically as a minimal wrapper of the Slack API.

**Comment by dinodsaurus** [comment]
Thanks a lot for this idea..
I had a spare evening so I made this package: https://github.com/twobucks/slack-message
If you have any suggestions how to improve it just ping me 👍

**Comment by mikaelbr** [comment]
👊 💪 That is fantastic. Great to see an idea get made that quickly and even before I "announce" the initiative! I'll test it out over the weekend.

Some suggestions from the top of my head:
- It might be smart to include a `files` property in your package.json so the consumers don't have do download your tests and what not. Saving some space and unnecessary download time.
- Maybe include an example Travis CI usage for instance? So users can see what it can be used for. This could also be a part of the README, for instance.

Thanks for reporting back to the repo with your implemented solution. I hope if you get any ideas of your own that you don't have time for, or you find time to do another you come back. And if you liked this concept, please help me share it when i "launch" it. I think maybe the best time to launch something to get traction is on week days, so I'll wait until over the weekend to release it unto the world.

**Comment by dinodsaurus** [comment]
You made good points, will hack on it a bit more tomorrow.
I will definitely share it because its a really cool project! 💃

**Comment by shime** [comment]
Thanks for the idea, Mikael. We've polished the package over the weekend.

Love the idea behind this repo, much better alternative than keeping ideas in Evernote notes and letting them be forgotten. I'll post some of my ideas soon.

We'll do our best to share it as much as we can when you launch it.

**Comment by mikaelbr** [comment]
That sounds great, @shime! I think for this initiative to work we need to keep the input flow as high as or higher than the output, so we need all ideas we can get 😃 

I'm planning on releasing it maybe tonight (Monday Night in GMT Timezone), what do you think?

**Comment by shime** [comment]
Thanks, I was thinking of sharing all the ideas, but maybe that would be perceived as too spammy. 

I'm not really the one who should give advice about this, but here goes.

I would look for the overlap of EU/US times for releasing it, so maybe 2PM GMT would work. Early morning in US and not too late in the evening for EU.

**Comment by mikaelbr** [comment]
Thanks. Great tip!

**Comment by mikaelbr** [comment]
I wrote a couple of words about the initiative here https://medium.com/@mikaelbrevik/open-source-ideas-initiative-ca747121ac34#.fdufq2v0b

**Comment by shime** [comment]
Great, shared it on [Hacker News](https://news.ycombinator.com/item?id=12726627) and [Reddit](https://www.reddit.com/r/programming/comments/57ybj8/open_source_ideas_initiative/) for maximum exposure!

**Comment by mikaelbr** [comment]
Nice. Thanks for all your help 🍰
